### ISSUE TITLE
Is this project official?

### ISSUE THREAD

**Issue by vzex** [Photocentric3D/Photonic3D-Dev#1]
Yesterday,  I found the project for process .cws files on pi:https://github.com/area515/Photonic3D
And then I searched github and find this. So I just wonder what's the different between the two project?
And does pi support 2k output ?(Because my dlp printer's screen is 2k lcd).I installed area515 version last night, and printed a .cws file, but the printer just moved z to zero and stoped

**Comment by kloknibor** [comment]
Hi vzex,

The official Photonic3D is the one in area515, we are just forking the project here to make a Photonic3D version which will fit our needs. So we use Photonic3D as base to create our own software!

Yes the pi gpu is capable of even higher resolutions, although the other components in the pi might hold you from improving it too much. Basically how higher the resolution how lower the refresh rate needs to be, also you will hit limits with RAM and your pi will heat up a lot more.

May I ask if you have an Photocentric printer? If it is an LC10 than the support for that printer is implemented in the normal area515. You don't even need to use .cws files but you could just set the exposure time and start printing with an .stl! or use slacer to generate zip files for more complicated objects ;)!

For your current issue I would like to point you back to area515, this way we won't shatter the conversation about the issue and for this reason I will close this issue.

Thank you!

**Comment by vzex** [comment]
My printer is not Photocentric , just a printer developed by oneself, and works well with creation workshop,so I wanna find a webserver to control it offline without pc.Thanks very much, the area515 just works fine now.
